# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mL5gS12xxcjABN-h0ecLG87TQP4WE3iv
"""

# nuts_bolts_dfs.py

MAX_HEIGHT = 4
MAX_DEPTH = 91


START = (
    ("R", "B", "O", "G"),
    ("R", "F", "B", "G"),
    ("R", "W", "B", "K"),
    ("Z", "K", "Y", "O"),
    ("Z", "S", "Z", "O"),
    ("Z", "W", "P", "F"),
    ("P", "P", "Y", "S"),
    ("Y", "F", "P", "S"),
    ("G", "W", "K", "W"),
    ("S", "R", "K", "N"),
    ("G", "F", "O", "N"),
    ("N", "Y", "B", "N"),
    (),
    ()
)


visited = set()

nodes_checked = 0
branch_number = 0
FIRST_LEVEL_BRANCHES = 0
FIRST_LEVEL_DONE = 0



# ---------------------------------
# Проверка победы
# ---------------------------------

def is_solved(state):

    for peg in state:

        if len(peg) == 0:
            continue

        # каждая заполненная шпилька
        # должна иметь 4 одинаковых цвета

        if len(peg) != MAX_HEIGHT:
            return False

        if len(set(peg)) != 1:
            return False

    return True

def is_completed_peg(peg):

    if len(peg) == 0:
        return False

    return len(set(peg)) == 1

# ---------------------------------
# Возможные ходы
# ---------------------------------

def get_possible_moves(state):

    moves = []

    for start in range(len(state)):

        source = state[start]

        if len(source) == 0:
            continue






        color = source[-1]


        # сколько одинаковых сверху
        count = 1

        for i in range(len(source)-2, -1, -1):

            if source[i] == color:
                count += 1
            else:
                break



        for target in range(len(state)):

            if target == start:
                continue


            dest = state[target]
            # запрещаем перенос одноцветной группы на пустую шпильку

            if len(dest) == 0 and is_completed_peg(source):

                continue

            # нет места
            if len(dest) >= MAX_HEIGHT:
                continue


            # пустая или сверху такой же цвет
            if len(dest) == 0 or dest[-1] == color:


                # сколько реально можно перенести

                free_space = MAX_HEIGHT - len(dest)

                amount = min(count, free_space)


                moves.append(
                    {
                        "color": color,
                        "from": start,
                        "to": target,
                        "count": amount
                    }
                )

    return moves





# ---------------------------------
# Выполнение хода
# ---------------------------------

def make_move(state, move):

    board = [list(x) for x in state]


    source = board[move["from"]]
    target = board[move["to"]]


    amount = move["count"]


    for _ in range(amount):

        target.append(source.pop())


    return tuple(
        tuple(x) for x in board
    )


def print_branch_end(number, path, reason, depth):

    print("\n==============================")

    print(
        "Ветка №",
        number,
        "завершена"
    )

    print(
        "Причина:",
        reason
    )


    print(
        "Глубина:",
        depth
    )




    print("==============================\n")


# ---------------------------------
# DFS поиск
# ---------------------------------

def dfs(state, depth, path):

    global nodes_checked
    global branch_number
    global FIRST_LEVEL_BRANCHES
    global FIRST_LEVEL_DONE


    nodes_checked += 1


    if is_solved(state):

        print("\nРЕШЕНИЕ НАЙДЕНО!")

        return path

    if depth >= MAX_DEPTH:

        branch_number += 1

        print_branch_end(
            branch_number,
            path,
            "достигнута максимальная глубина",
            depth
        )

        return None





    moves = get_possible_moves(state)


    # на стартовом состоянии запоминаем количество веток

    if depth == 0:

            FIRST_LEVEL_BRANCHES = len(moves)






    # если ходов нет - ветка закончилась

    if len(moves) == 0:

        branch_number += 1

        print_branch_end(
            branch_number,
            path,
            "нет возможных ходов",
            depth
        )

        return None


    for move_number, move in enumerate(moves, 1):


        new_state = make_move(
            state,
            move
        )


        # защита от циклов

        if new_state in visited:
            continue


        visited.add(new_state)



        result = dfs(
            new_state,
            depth + 1,
            path + [move]
        )


        if result is not None:

            return result


        if depth == 0:

            FIRST_LEVEL_DONE += 1

            print(
                "Прогресс первого уровня:",
                FIRST_LEVEL_DONE,
                "/",
                FIRST_LEVEL_BRANCHES
            )







    return None






# ---------------------------------
# Печать решения
# ---------------------------------

def print_solution(path):

    print("\nПоследовательность ходов:\n")


    for i, move in enumerate(path,1):

        print(
            i,
            ":",
            move["color"],
            "из",
            move["from"] + 1,
            "в",
            move["to"] + 1,
            "количество",
            move["count"]
        )






# ---------------------------------
# Запуск
# ---------------------------------

if __name__ == "__main__":


    print("Старт поиска DFS")

    visited.add(START)


    solution = dfs(
        START,
        0,
        []
    )


    if solution:

        print_solution(solution)

    else:

        print(
            "\nРешение не найдено"
        )


    print(
        "\nВсего проверено состояний:",
        nodes_checked
    )